version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: node-template
    restart: always
    environment:
      POSTGRES_USER: localpg
      POSTGRES_PASSWORD: localpg
      POSTGRES_DB: localpg
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: