import dotenv from "dotenv";

dotenv.config();

const OPEN_DOTA_BASE_URL = process.env.OPEN_DOTA_BASE_URL || "";

/** SECONDS  */

// Requests per minute
const SHORT_TERM_RATE_LIMIT = process.env.SHORT_TERM_RATE_LIMIT || "";

// Requests per day
const DAILY_RATE_LIMIT = process.env.DAILY_RATE_LIMIT || "";

// Requests per month
const MONTHLY_RATE_LIMIT = process.env.MONTHLY_RATE_LIMIT || "";

const PORT = process.env.PORT || 3000;
const DISCORD_BOT_TOKEN = process.env.DISCORD_BOT_TOKEN || "";
const DISCORD_BOT_CLIENT_ID_OAUTH = process.env.DISCORD_BOT_CLIENT_ID_OAUTH || "";
const DISCORD_BOT_CLIENT_SECRET_OAUTH = process.env.DISCORD_BOT_CLIENT_ID_OAUTH || "";
const DISCORD_GENERATED_OAUTH_URL = process.env.DISCORD_GENERATED_OAUTH_URL || "";

const DISCORD_BOT_APPLICATION_ID = process.env.DISCORD_BOT_APPLICATION_ID || "";

const LINKLE_SERVER_ID = process.env.LINKLE_SERVER_ID || "";
const TESTBOT_SERVER_ID = process.env.TESTBOT_SERVER_ID || "";

export {
	OPEN_DOTA_BASE_URL,
	SHORT_TERM_RATE_LIMIT,
	DAILY_RATE_LIMIT,
	MONTHLY_RATE_LIMIT,
	PORT,
	DISCORD_BOT_TOKEN,
	DISCORD_BOT_CLIENT_ID_OAUTH,
	DISCORD_BOT_CLIENT_SECRET_OAUTH,
	DISCORD_GENERATED_OAUTH_URL,
	DISCORD_BOT_APPLICATION_ID,
	LINKLE_SERVER_ID,
	TESTBOT_SERVER_ID,
};
